version: '3.4'

services:
  postgres.data:
    image: postgres:alpine

  testprogrammationconformit:
    build: .
    ports:
      - 5001:80
    image: ${DOCKER_REGISTRY-}testprogrammationconformit
    environment:
      - ConnectionStrings__ConformitDb=Host=postgres.data;Port=55432;Database=ConformitDb;Username=postgres;Password=${POSTGRES_PASSWORD:-admin}
